/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tic_tac_toe_backend.tic_tac_toe_backends.models.shared;




public class MoveParameter {
    
    public Long cellIndex;

    public MoveParameter withCellIndex(Long cellIndex) {
        this.cellIndex = cellIndex;
        return this;
    }
    
    
    public MoveParameterMove move;

    public MoveParameter withMove(MoveParameterMove move) {
        this.move = move;
        return this;
    }
    
    public MoveParameter(){}
}
