/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tic_tac_toe_backend.tic_tac_toe_backends.models.shared;




public class MoveAfterStatePossibleMovesAfterState {
    
    public MoveAfterStatePossibleMovesAfterStateGrid grid;

    public MoveAfterStatePossibleMovesAfterState withGrid(MoveAfterStatePossibleMovesAfterStateGrid grid) {
        this.grid = grid;
        return this;
    }
    
    
    public MoveAfterStatePossibleMovesAfterStateStartingMark startingMark;

    public MoveAfterStatePossibleMovesAfterState withStartingMark(MoveAfterStatePossibleMovesAfterStateStartingMark startingMark) {
        this.startingMark = startingMark;
        return this;
    }
    
    public MoveAfterStatePossibleMovesAfterState(){}
}
