/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tic_tac_toe_backend.tic_tac_toe_backends.models.shared;




public class MoveAfterStatePossibleMovesBeforeState {
    
    public MoveAfterStatePossibleMovesBeforeStateGrid grid;

    public MoveAfterStatePossibleMovesBeforeState withGrid(MoveAfterStatePossibleMovesBeforeStateGrid grid) {
        this.grid = grid;
        return this;
    }
    
    
    public MoveAfterStatePossibleMovesBeforeStateStartingMark startingMark;

    public MoveAfterStatePossibleMovesBeforeState withStartingMark(MoveAfterStatePossibleMovesBeforeStateStartingMark startingMark) {
        this.startingMark = startingMark;
        return this;
    }
    
    public MoveAfterStatePossibleMovesBeforeState(){}
}
