/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tic_tac_toe_backend.tic_tac_toe_backends.models.shared;




public class MoveAfterStatePossibleMoves {
    
    public MoveAfterStatePossibleMovesAfterState afterState;

    public MoveAfterStatePossibleMoves withAfterState(MoveAfterStatePossibleMovesAfterState afterState) {
        this.afterState = afterState;
        return this;
    }
    
    
    public MoveAfterStatePossibleMovesBeforeState beforeState;

    public MoveAfterStatePossibleMoves withBeforeState(MoveAfterStatePossibleMovesBeforeState beforeState) {
        this.beforeState = beforeState;
        return this;
    }
    
    
    public Long cellIndex;

    public MoveAfterStatePossibleMoves withCellIndex(Long cellIndex) {
        this.cellIndex = cellIndex;
        return this;
    }
    
    
    public MoveAfterStatePossibleMovesMark mark;

    public MoveAfterStatePossibleMoves withMark(MoveAfterStatePossibleMovesMark mark) {
        this.mark = mark;
        return this;
    }
    
    public MoveAfterStatePossibleMoves(){}
}
