/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tic_tac_toe_backend.tic_tac_toe_backends.models.shared;




public class MoveAfterState {
    
    public MoveAfterStateCurrentMark currentMark;

    public MoveAfterState withCurrentMark(MoveAfterStateCurrentMark currentMark) {
        this.currentMark = currentMark;
        return this;
    }
    
    
    public Boolean gameNotStarted;

    public MoveAfterState withGameNotStarted(Boolean gameNotStarted) {
        this.gameNotStarted = gameNotStarted;
        return this;
    }
    
    
    public Boolean gameOver;

    public MoveAfterState withGameOver(Boolean gameOver) {
        this.gameOver = gameOver;
        return this;
    }
    
    
    public MoveAfterStateGrid grid;

    public MoveAfterState withGrid(MoveAfterStateGrid grid) {
        this.grid = grid;
        return this;
    }
    
    
    public MoveAfterStatePossibleMoves[] possibleMoves;

    public MoveAfterState withPossibleMoves(MoveAfterStatePossibleMoves[] possibleMoves) {
        this.possibleMoves = possibleMoves;
        return this;
    }
    
    
    public MoveAfterStateStartingMark startingMark;

    public MoveAfterState withStartingMark(MoveAfterStateStartingMark startingMark) {
        this.startingMark = startingMark;
        return this;
    }
    
    
    public Boolean tie;

    public MoveAfterState withTie(Boolean tie) {
        this.tie = tie;
        return this;
    }
    
    
    public MoveAfterStateWinner winner;

    public MoveAfterState withWinner(MoveAfterStateWinner winner) {
        this.winner = winner;
        return this;
    }
    
    
    public Long[] winningCells;

    public MoveAfterState withWinningCells(Long[] winningCells) {
        this.winningCells = winningCells;
        return this;
    }
    
    public MoveAfterState(){}
}
