/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tic_tac_toe_backend.tic_tac_toe_backends.models.shared;




public class MoveAfterStatePossibleMovesBeforeStateGrid {
    
    public String cells;

    public MoveAfterStatePossibleMovesBeforeStateGrid withCells(String cells) {
        this.cells = cells;
        return this;
    }
    
    public MoveAfterStatePossibleMovesBeforeStateGrid(){}
}
