/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tic_tac_toe_backend.tic_tac_toe_backends.models.shared;



/**
 * Move - A Move containing the before and after GameStates.
 */

public class Move {
    
    public MoveAfterState[] afterState;

    public Move withAfterState(MoveAfterState[] afterState) {
        this.afterState = afterState;
        return this;
    }
    
    public Move(){}
}
