/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tic_tac_toe_backend.tic_tac_toe_backends.models.shared;



/**
 * Version - The package version.
 */

public class Version {
    
    public String version;

    public Version withVersion(String version) {
        this.version = version;
        return this;
    }
    
    public Version(){}
}
