/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tic_tac_toe_backend.tic_tac_toe_backends.utils;

import java.net.http.HttpRequest.BodyPublisher;

public class SerializedBody {
    public String contentType;
    public BodyPublisher body;
}
